"""Turn certs/cacert.pem (Mozilla's roots, from https://curl.se/ca/cacert.pem)
into tinc_roots.h: one BearSSL trust anchor per root, looked up by the SHA-256
of its subject DN, as the ESP8266 BearSSL's dynamic trust-anchor hook wants.
The firmware's CA roots are exactly this file, so a reflash updates them.

PlatformIO runs this before each build (extra_scripts = pre:tools/gen_roots.py)
and writes the header to $BUILD_DIR/roots/. Standalone:
    python tools/gen_roots.py certs/cacert.pem out.h
"""
import base64
import hashlib
import os
import re
import sys

RSA = "2a864886f70d010101"          # rsaEncryption
EC = "2a8648ce3d0201"               # id-ecPublicKey
CURVES = {"2a8648ce3d030107": 23,   # secp256r1 (BR_EC_secp256r1)
          "2b81040022": 24,         # secp384r1
          "2b81040023": 25}         # secp521r1


def tlv(d, i):
    """(tag, start of value, end of value) of the DER element at d[i]."""
    tag, n = d[i], d[i + 1]
    i += 2
    if n & 0x80:
        k = n & 0x7F
        n = int.from_bytes(d[i:i + k], "big")
        i += k
    return tag, i, i + n


def children(d, i):
    _, s, e = tlv(d, i)
    out = []
    while s < e:
        out.append(s)
        s = tlv(d, s)[2]
    return out


def uint(d, i):
    _, s, e = tlv(d, i)
    return d[s:e].lstrip(b"\0")


def anchor(der):
    """(sha256 of subject DN, key type, curve, key bytes) or None if unusable."""
    tbs = children(der, 0)[0]
    f = children(der, tbs)
    if der[f[0]] == 0xA0:           # [0] version
        f = f[1:]
    subject, spki = f[4], f[5]
    dn = der[subject:tlv(der, subject)[2]]
    alg, bits = children(der, spki)
    algf = children(der, alg)
    oid = der[tlv(der, algf[0])[1]:tlv(der, algf[0])[2]].hex()
    _, s, e = tlv(der, bits)
    key = der[s + 1:e]               # skip the unused-bits byte
    if oid == RSA:
        n, ex = children(key, 0)
        n, ex = uint(key, n), uint(key, ex)
        return hashlib.sha256(dn).digest(), "RSA", 0, n, ex
    if oid == EC:
        c = der[tlv(der, algf[1])[1]:tlv(der, algf[1])[2]].hex()
        if c in CURVES:
            return hashlib.sha256(dn).digest(), "EC", CURVES[c], key, b""
    return None


def c_bytes(b):
    return ",".join("0x%02X" % x for x in b)


def generate(pem_path, out_path):
    pem = open(pem_path, encoding="utf-8").read()
    blobs = re.findall(r"-----BEGIN CERTIFICATE-----(.*?)-----END CERTIFICATE-----", pem, re.S)
    rows, data, skipped = [], bytearray(), 0
    for b in blobs:
        a = anchor(base64.b64decode("".join(b.split())))
        if not a:
            skipped += 1
            continue
        h, kind, curve, k1, k2 = a
        rows.append("    {{%s}, %d, %d, %d, %d, %d}" % (
            c_bytes(h), kind == "EC", curve, len(k1), len(k2), len(data)))
        data += k1 + k2
    with open(out_path, "w") as f:
        f.write("/* Generated by tools/gen_roots.py from %s; do not edit. */\n"
                "#define TINC_ROOT_COUNT %d\n"
                "static const tinc_root tinc_roots[] PROGMEM = {\n%s\n};\n"
                "static const uint8_t tinc_root_keys[] PROGMEM = {%s};\n"
                % (os.path.basename(pem_path), len(rows), ",\n".join(rows), c_bytes(data)))
    return len(rows), skipped


if __name__ == "__main__" and len(sys.argv) == 3:
    print("roots: %d, skipped %d" % generate(sys.argv[1], sys.argv[2]))
else:
    Import("env")  # noqa: F821 (PlatformIO SCons)
    root = env.subst("$PROJECT_DIR")  # noqa: F821
    out_dir = os.path.join(env.subst("$BUILD_DIR"), "roots")  # noqa: F821
    pem = os.path.join(root, "certs", "cacert.pem")
    out = os.path.join(out_dir, "tinc_roots.h")
    os.makedirs(out_dir, exist_ok=True)
    if not os.path.exists(out) or os.path.getmtime(out) < os.path.getmtime(pem):
        generate(pem, out)
    env.Append(CPPPATH=[out_dir])  # noqa: F821
